# Generated by Django 3.0.8 on 2020-07-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200731_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchers', to='auctions.Auction'),
        ),
    ]
