# Generated by Django 3.0.8 on 2020-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_watchlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='creator',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlists',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='watchers', to='auctions.Auction'),
        ),
    ]
