# Generated by Django 3.0.8 on 2020-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200804_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='open_status',
            field=models.BooleanField(default=True),
        ),
    ]
